### ISSUE TITLE
Feature Request: Option to enable/disable "Show details for all processes" together with "Start when I log on"

### ISSUE THREAD

**Issue by merceyz** [processhacker2/processhacker2#100]

**Comment by dmex** [comment]
Are you asking for a feature to automatically elevate Process Hacker on startup?

**Comment by TETYYS** [comment]
https://wj32.org/processhacker/forums/viewtopic.php?f=5&t=2362&p=7678#p7678

**Comment by merceyz** [comment]
> Are you asking for a feature to automatically elevate Process Hacker on startup?

Yes

**Comment by dmex** [comment]
Auto-elevation opens a security hole in the operating system because it allows anything to bypass the user and automatically perform actions as an administrator... 😨 

Process Hacker includes command line options to terminate/suspend processes and if we include an option to auto-elevate then malware or spyware could terminate/suspend processes from an administrative context without prompting the user for those privileges.

There are some solutions to this:
1. Right-click the Toolbar and add the "Show details" button for quicker elevation.
2. Keep Process Hacker running continuously in the system tray.
3. Use the method suggested by @TETYYS 

I always use options 1 and 2 depending on what I'm doing and I don't see more than one UAC prompt a day (or week on my home machine since it's running 24/7)... IMO option 3 also creates a security issue and I don't recommend it.

If you have some solutions to mitigate the risk of auto-elevation then please reopen the ticket so I can add support for that feature 👍
