### ISSUE TITLE
Building with Windows 10 SDK Preview Build 15021

### ISSUE THREAD

**Issue by umokk** [processhacker2/processhacker2#103]
Building Process Hacker with Windows 10 SDK Preview Build 15021 fails with linker error "unresolved external symbol __security_check_cookie_ex".

**Comment by dmex** [comment]
You need to add **bufferoverflow.lib** to the project properties > Linker > Input > Additional Dependencies option.

The missing lib file appears to be a regression in the SDK since the /GS option previously included that lib file by default... I'll push the fix into master if the issue still exists in the RTM build.

**Comment by umokk** [comment]
Thank you for your reply.

**Comment by dmex** [comment]
This ticket needs to stay open until the missing lib file is resolved 👍
