### ISSUE TITLE
[question] is malware capable of hiding itself from ph2

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [processhacker2/processhacker2#107]
Hi there,

I was wondering if PH2 was capable of displaying malware which hides from other task managers if you make use of the kernel-mode driver?

I'm not savvy, just curious, I read recently that malware which conceals its process entirely is becoming more common and I was shocked to learn that it even exists, I'm only used to ever seeing malware that 1. parrots names of system processes, 2. uses system processes, 3. uses its own names and or a combination of all 3.

I've also read about malware that actively tries to determine if it's on a virtual machine or not, I'm sure these are probably just the tip of the iceberg in terms of the ever changing and accelerating malware landscape.

Thanks.

**Comment by dmex** [comment]
> malware which conceals its process entirely

After you change the code, how does malware remain 'entirely' concealed or continue working? Malware can only remain hidden if both Process Hacker and Windows never change. If someone breaks through the back window you can remove the window, if it's a bad neighborhood you can move the house 😄 

> malware that actively tries to determine if it's on a virtual machine or not

If it doesn't run when it detects virtualization then you at least know anything running in that environment is secure 👍 

> I was wondering if PH2 was capable of displaying malware which hides from other task managers

If malware or anything else has a technique for hiding or blocking Process Hacker then you or anyone else can rewrite the source code and make the necessary changes depending on the location or environment. 

You also won't see instructions for modifying Process Hacker on Github or elsewhere because they can just update their code and detect those changes 😃

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
So I suppose this is true that some software/malware is capable of cloaking itself from task managers, that was my basic question. I appreciate all of the information, I do use Kaspersky Internet Security :rofl: :rofl: :rofl: and common sense. I REALLY enjoy process hacker as it has replaced numerous tools for me and it's got access to so much more.

I also use Steam :octopus: :octocat:, and games with EasyAntiCheat :cold_sweat:. I understand your position of course, this answered my question as to weather or not it was real and that it can happen. :100: 

Very cool, thanks for the information.
