### ISSUE TITLE
MS changed patch to msbuild.exe binary thats needed update ./build/internal/build.ps1

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#109]
Summary build problem:

.\ProcessHacker\bld.cmd"
Getting build information...  3.0.404 (Update solutions to Visual Studio 2017)
Setting up signature files [SKIPPED] (VirusTotal build key)
Building ProcessHacker        [ERROR] C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [.\ProcessHacker\trunk\phlib\phlib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [.\ProcessHacker\trunk\phlib\phlib.vcxproj]

VS2017 installed, I set %VS150COMNTOOLS% (installer not set any enveronment, but files is copyid), but this messages is display an over and an over.

also I have build error for x64 plugin Extended tools

Error C1001 Internal error in to compiled files :: ExtendedNotifications :: .\processhacker\trunk\plugins\extendednotifications\gntp-send\growl.c string 70

then have Access Violation in to link.exe, then stop ...

Also question do you enveronment needed make? Curreent enveronment list:

Path=
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.py;.pyw
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
VS100COMNTOOLS=$INSTALLDIR\Common7\Tools\
VS140COMNTOOLS=$INSTALLDIR\Common7\Tools\
VS150COMNTOOLS=$INSTALLDIR\Common7\Tools\
VSSDK140Install=$INSTALLDIR\VSSDK\
VSSDK150Install=$INSTALLDIR\VSSDK\

Help needed...

**Comment by VictorVG** [comment]
I found thats point needed correct - is ./build/internal\build.ps1 :: function BuildSolution([string] $FileName)

Old value **$msBuild =** :
```
function BuildSolution([string] $FileName)
{
    # Set msbuild path (TODO: Do we need the 32bit version of MSBuild for x86 builds?)
   # Needed change patch up to new msbuild.exe location
    $msBuild = "${env:ProgramFiles(x86)}\MSBuild\14.0\bin\amd64\MSBuild.exe"
    # Get base file name
```
needed change up to new value **$msBuild =** :
```
function BuildSolution([string] $FileName)
{
    # Set msbuild path (TODO: Do we need the 32bit version of MSBuild for x86 builds?)
    # Change patch up to new msbuild.exe location!
    $msBuild = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\{vs_type}\MSBuild\15.0\Bin\amd64\MSBuild.exe"
    # Get base file name
```
then M$ move msbuild in to new location and build is [SUCCESS].

**Comment by dmex** [comment]
Yep, the location for msbuild has been changed but that is not the only problem.

The main issue is that since msbuild is now part of the Visual Studio installation there are other issues:
* All msbuild related registry configuration (e.g. installation location) are now non existent.
* Separate folder paths for msbuild depending if Community, Professional or Enterprise versions of Visual Studio were installed.
* Users can customize the install location for Community, Professional and Enterprise in completely different folders and hard drives.

We need to use the ISetupConfiguration2 COM interface in order to discover the installation path of Visual Studio and check for msbuild... I'm testing those changes but it'll take some time due to the number of Visual Studio editions and missing msbuild documentation.

**Comment by VictorVG** [comment]
I understand, how can I help?

**Comment by VictorVG** [comment]
Far Manager changelog - build 4910 (quote for information):

> **Drkns** 08/03/2017 19:14:38 +0000 - build 4910
> 
> 1. Remove constexpr from static objects - in VS2017 it is still worse than before.

**Comment by VictorVG** [comment]
Latest build report ( 18:27:29 +0300 10-03-2017) then using VC++2015 Update3:

> 3.0. (Update solutions to Visual Studio 2017)
> Setting up signature files [SKIPPED] (VirusTotal build key)
> Building ProcessHacker        [SUCCESS]
> Copying text files            [SUCCESS]
> Copying signed KPH driver   [SUCCESS]
> Building SDK headers   [SUCCESS]
> Setting up public headers   [SUCCESS]
> Setting up resource headers   [SUCCESS]
> Setting up plugin lib files   [SUCCESS]
> Building Plugins        [SUCCESS]
> Building ExtraPlugins        [SUCCESS]
> Setting up Wow64 files       [SUCCESS]
> Create PluginsData dir   [SUCCESS]
> Copy Terminator driver   [SUCCESS]
> Building Setup    [SUCCESS]
> Building Process Hacker SDK      [SUCCESS]
> Building ProcessHacker Zip      [SUCCESS]
> Building source tarball       [SUCCESS]
> Generating checksums        [SUCCESS]
> Update build signatures [SKIPPED] (VirusTotal build key)
> Cleaning up...
> 
> Build Time: 1 minute(s), 37 second(s)

**P.S.**

_And here I think - and can make to in the same SumatraPDF, NetBox, Rufus - while leaving as the main compiler VC14 (VS2015) the blessing in the standard C++11 we have no problems with the assembly, and for VC15 (VS2017) in the critical for VC15 places the code to put conditional compilation directives which will switch it to the "correct" code from its point of view and calmly bring the code to the requirements of the standard C++14._

**Comment by VictorVG** [comment]
Ok! I go to test it.

**Comment by gvanem** [comment]
Since this PR was *fixed* you seems to have rewritten the PowerShell scripts into CSharp. But it's still a problem for me; `CustomBuildTool.exe` consistently reports `MsBuild not installed. Exiting.`

Even with a brand new install of Visual-Studio 2017. But the `%windir%\System32\where.exe msbuild.exe` reports 2 hits on my PATH:
```
f:\gv\vc_2017\MSBuild\15.0\Bin\MSBuild.exe
c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
```
Why not do:
```
MSBuildExePath = VisualStudio.GetFilePathFromPath("msbuild.exe");
```
then the `VisualStudio.GetMsbuildFilePath()` approach?

These trivial problems made me just cook up some GNU-makefiles that works fine.

**Comment by dmex** [comment]
@gvanem 

>  But the %windir%\System32\where.exe msbuild.exe reports 2 hits on my PATH

Have you modified your PATH variable? I've tested a few machines and those locations are not the defaults and don't match my results.

>  a brand new install of Visual-Studio 2017

Are you using the standard Visual Studio installer or something else?

> Why not do... VisualStudio.GetFilePathFromPath... then the VisualStudio.GetMsbuildFilePath() approach?

The where command searches the PATH variable. Your path variable has been modified to include folders that are non-standard and not the Windows defaults used by everyone else. I'll need more information about why your Windows installation is different before making that change.

> These trivial problems made me just cook up some GNU-makefiles that works fine.

Feel free to submit a PR or upload the files to https://gist.github.com/ and I'll include them with the project.

The CustomBuildTool doesn't do anything special here. You can simply open the ProcessHacker.sln file with Visual Studio and rebuild the project from the VS build menu (this also compiles the Plugin-SDK) and if you need plugins then open the \Plugins\Plugins.sln and use the same rebuild command... The end result is exactly the same as the build scripts.

**Comment by gvanem** [comment]
> Have you modified your PATH variable? 

Sure, all the time. But do you mean path-entries for VStudio stuff. No way, since I really hate VisualStudio, but I'm an avid user of it's cmd-line tools.

> .. non-standard and not the Windows defaults used by everyone else. 

I'm not sure what *Windows default* you mean since VisualStudio and all it's bloated packages are not part of a *default* Windows installation. I reinstalled VS-2017 2 days ago. I expected that the installer would update the Registry with those vital paths. Including the path I chose during the *Visual Studio Installer*. But apparently not. Seems my previous VS-2017 installation wasn't fully un-installed. AFAICR, there is a program that does this since the VisualStudio team is not up for it.

**Comment by dmex** [comment]
@gvanem 

> I expected that the installer would update the Registry with those vital paths. Including the path I chose during the Visual Studio Installer.

VS2017 doesn't store the installation location in the registry unfortunately. We use the vswhere.exe tool for locating the Visual Studio installation.

1) Open cmd and execute:
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"

2) Screenshot the results or upload the text to https://gist.github.com/

The vswhere tool should have the following output:
https://i.imgur.com/gfUgdvz.png
