### ISSUE TITLE
Process Hacker 2 acts veery strange after some time

### ISSUE THREAD

**Issue by TETYYS** [processhacker2/processhacker2#18]
After updating to 2.38 after some time it happens to act really strange before just not responding.

- Tray icons crash, just displays transparent square
- Scrolling the process list doesn't display processes, it just duplicates existing rendered graphics
- Displays scaled / distorted current rendered object artifacts on monitor (not only on PH window, also affects second monitor), here's part of bambalooza I've managed to snap http://i.imgur.com/7IO23cv.png
- ??????

**Comment by dmex** [comment]
Have you tried disabling plugins using the Options window and unticking "Enable plugins" on the general tab?

**Comment by TETYYS** [comment]
I've disabled some plugins and now I'm waiting because I didn't want to set up my columns again after disabling plugins. I'll backup settings.xml and disable all of them.

**Comment by TETYYS** [comment]
1h in, no problems

**Comment by dmex** [comment]
Why do you have UMDFHost Process Plugin? That was integrated with PH ages ago, you can remove it.

**Comment by TETYYS** [comment]
lmao

**Comment by TETYYS** [comment]
+ Emergency, Extended Notifications, Extended Services, Extended Tools, Firewall Monitor

**Comment by dmex** [comment]
Remove Firewall Monitor... It has some known issues.

**Comment by TETYYS** [comment]
I'll keep the PH running, see if it crashes

**Comment by TETYYS** [comment]
This time it crashed immediately when I tried to move CPU Average (60) column trough Choose columns... menu because when I dragged it, nothing happened. But I don't think it's the cause because when the bug happens, all GUI just keeps not responding, acts weirdly.
[crash](http://i.imgur.com/9I94Jqr.png)

**Comment by wj32** [comment]
Where did you get the extra plugins from? Make sure you're compiling them against the latest SDK.

**Comment by VictorVG** [comment]
On Win7 SP1 x64 this problem not exists. I use all PH2 v2.38+ Git plug-ins and plugins-extra kit..

**Comment by TETYYS** [comment]
I got extra plugins from latest Git repo and compiled with latest SDK.
I'll disable my plugins just to make sure and keep the PH running for a couple of hours.
Same Win as @VictorVG

**Comment by wj32** [comment]
No clear instructions to reproduce... I constantly run PH for hours/days without restarting and it seems fine to me :)

**Comment by klonos** [comment]
>  I constantly run PH for hours/days without restarting and it seems fine to me :)

Same here.

**Comment by TETYYS** [comment]
That was the case for me too before update, but now, something's strange happening.. :cry:

**Comment by VictorVG** [comment]
If the issue is the number of CPU cycles, then there is a clear taskhost system element is present in all problems and it looks like OS gives statistic's use them on all the CPU time together. I and without failure in the CPU::cycles digit rolls over. :)

Process Hacker 2.39.0.30:

![ph](https://cloud.githubusercontent.com/assets/906886/13502061/63ae2af8-e17a-11e5-8336-92efe8cef5e2.png)

Windows Task Manager:

![taskmaneger](https://cloud.githubusercontent.com/assets/906886/13502522/5b5b539c-e17c-11e5-9b71-023a789f8844.png)

System Explorer 7.0:

![se](https://cloud.githubusercontent.com/assets/906886/13502538/69202606-e17c-11e5-928e-18305069fe9c.png)


though like himself taskhost virtually idle.(????) I can assume that there is some incorrectness in the calculation of the time CPU usage in the Task Scheduler OS sits as so I have seen only in Windows and other OS I like "ghosts" have not met ...

**Comment by TETYYS** [comment]
are you dense

**Comment by dmex** [comment]
I've seen similar things when the desktop GDI resources are exhausted or something is using GDI incorrectly

**Comment by TETYYS** [comment]
Yeah, it just looks like objects have been free'd or something

**Comment by TETYYS** [comment]
Is this related? https://github.com/processhacker2/processhacker2/issues/21

**Comment by wj32** [comment]
@TETYYS No

**Comment by wj32** [comment]
It looks like something is deleting the font object that's being used by the standard controls.

**Comment by dmex** [comment]
I think this was caused by a bug in the way Taskbar Extensions was getting it's GDI handle for drawing the taskbar graphs every update interval (e.g. every second it was using the GDI handle from the main PH window instead of the desktop screen handle).

I've made some changes that should fix the issue (if it's indeed the cause).

**Comment by TETYYS** [comment]
This was indeed caused by Firewall Monitor plugin.

**Comment by dmex** [comment]
I've disabled process icons in the Firewall Monitor plugin...
