### ISSUE TITLE
System Information window taskbar button loses its icon after some time.

### ISSUE THREAD

**Issue by klonos** [processhacker2/processhacker2#28]
This is on a Win8.1 x64 machine where the taskbar buttons for applications are set to "Combine when taskbar is full" (the default is "Always combine, hide labels").

After some time (could be days or weeks actually because I have my laptop set to hibernate when I close the lid), the taskbar button loses its icon and it is replaced by a generic one. I just upgraded to the newly-released 2.39 and restarted PR, so it is fine for now. Soon as this happens again, I'll post a screenshot.

Does anyone else notice this? It is not a big thing for me, because the program functionality doesn't change. It is simply a minor annoyance.

Additional notes:
- The main window icon does not display this issue.
- Restarting PR fixes the issue.
- Next time it happens, I will also check to see if closing the System Info window and opening it again fixes the issue.

**Comment by dmex** [comment]
The system information window doesn't currently have an icon?

**Comment by klonos** [comment]
> After some time (could be days or weeks ...the taskbar button loses its icon...

**Comment by klonos** [comment]
Alright... after 4 days running without any issue, today it happened. So here's a screenshot of it:

![ph-taskbar_button_loses_icon](https://cloud.githubusercontent.com/assets/2423362/14226980/e12a6d40-f93d-11e5-8f41-86965222986f.png)

**Comment by dmex** [comment]
Process Hacker doesn't load and set window icons for child windows (e.g. The System Information window).

Explorer copies the main window icon to all child windows if they don't have their own icons. Your machine seems to somehow lose the Explorer icon cache and shows the child windows with the default shell icon.

Windows Shell bug or Process Hacker bug?

**Comment by klonos** [comment]
>Windows Shell bug or Process Hacker bug?

@dmex I wouldn't be able to tell, I'm just reporting something that happens just with PH. None of my other taskbar buttons loose their icons - ever. But then again, you are right that with the System Info window it is a special case since it is a child window. I wish I could help.

**Comment by klonos** [comment]
FTR, I see this with the latest nightly build too.

**Comment by dmex** [comment]
The issue is with how different versions of the Windows shell handle the application icon.

Process Hacker doesn't load or set the icons for the System Information window or other windows. The Windows shell automatically extracts the first icon from the executable and uses it for the entire application.

Fixing this issue requires loading the same icon twice and then updating the window icon (twice) with the new bitmap and I don't see the point of the additional performance cost just to fix Windows shell bugs on  older versions of Windows and a 16x16 icon that's just eye candy.

If anyone wants to spend time fixing this and making a patch then I'll merge it.

**Comment by dmex** [comment]
Fixed in recent nightly builds 👍
