### ISSUE TITLE
GEO IP Listing On Network Addresses

### ISSUE THREAD

**Issue by mbostwick** [processhacker2/processhacker2#50]
Having a geo ip listing on the network port listing along with a flag indicating the country of orgin, would be helpful when looking at the network ports.

**Comment by TETYYS** [comment]
honestly good idea

**Comment by mbostwick** [comment]
I wasn't sure, where to route what issues, so I started here, and hoped if this wasn't the place, someone would tell me. When I have time I'd really just like to make this a pull request, and write the code to support this, but I'm time limited atm..

**Comment by VictorVG** [comment]
The idea itself is beautiful, but the accuracy of determining the location on the server GEO IP close to zero as IETF and RIPE does not guarantee that issued the machine IP is physically located in a particular country, so it is necessary to trace the entire chain of route servers, but it does not give a guarantee that his last segment does not include the chain of repeaters allowing to spread the final host and the point of its connection to the WAN tens of thousands of kilometers. Sam recently successfully solved a similar problem at work.

So much sense in such information not see. In order to learn about the location of GRO-host is enough to read the report WhoIs.

**Comment by TETYYS** [comment]
get a load of this lunatic

**Comment by dmex** [comment]
Good idea... I'll look into how this can be added and update the ticket once something is available.

**Comment by dmex** [comment]
Is the flag and country image what you wanted (based on the remote IP for a connection)?

http://i.imgur.com/YW0afQz.png

**Comment by VictorVG** [comment]
Here I am FOR! In this sense, I like the implementation in addon [**Flagfox**](https://flagfox.wordpress.com/)  for SeaMonkey / FireFox - 

![1](https://cloud.githubusercontent.com/assets/906886/17279578/5e147634-5780-11e6-9e70-5db4deb8331d.png)

сonvenient because it is immediately evident country and do not knowingly cause WhoIs ... :+1:

**Comment by dmex** [comment]
@VictorVG 

https://www.youtube.com/watch?v=YpuRcmPnSTM

**Comment by TETYYS** [comment]
@dmex looks nice :+1:

**Comment by dmex** [comment]
I've uploaded the plugin here:
https://wj32.org/processhacker/forums/viewtopic.php?t=2406

Let me know if there are any issues so I can close this ticket :P

**Comment by mbostwick** [comment]
Works, Great!!!
Thanks everyone!

**Comment by dmex** [comment]
There are still some issues so I'll leave this ticket open for now...

There was also a bug in the version I uploaded on the forum... Please re-download the plugin if you have already downloaded it 👍

**Comment by dmex** [comment]
Nightly builds now include GeoIP information including Country flag, country name and estimated distance :grin:

https://wj32.org/processhacker/nightly.php
