### ISSUE TITLE
Issue in hndlinfo.c

### ISSUE THREAD

**Issue by ZaronZ** [processhacker2/processhacker2#82]
### phlib\hndlinfo.c

- PhGetObjectTypeNumber function have memory leak, missing PhFree on some returns
- In PhEnumObjectTypes function not correct call of NtQueryObject, please add ReturnLength argument. Some OS can produce STATUS_ACCESS_VIOLATION when ReturnLength is NULL.

**Comment by dmex** [comment]
Thanks! I've fixed the PhGetObjectTypeNumber leaks in PR #83 (just awaiting approval to merge since @wj32 owns that function)

Do you know exactly which OSs have issues with NtQueryObject? It's officially documented that the ReturnLength value is optional and I've never seen a crash from that function: https://msdn.microsoft.com/en-us/library/bb432383.aspx

**Comment by dmex** [comment]
Fixed by PR #133
