### ISSUE TITLE
Uninitialized value in System Information at wireless adapter?

### ISSUE THREAD

**Issue by TETYYS** [processhacker2/processhacker2#89]
System Information says that my wireless adapter link speed is 2097152 TB/s. Possible usage of uninitialized value?

EDIT: Not likely since it stays 2097152 TB/s after PH restart.

![processhacker_2016-12-21_01-38-29](https://cloud.githubusercontent.com/assets/3091645/21372168/52c58b0c-c71e-11e6-9630-87e9a87eb9ea.png)

**Comment by dmex** [comment]
How do you read an 'uninitialized value' without crashing the program? You don't since it'll crash the program ;)

That's the actual value returned by the device driver and can also be sometimes seen after disabling the adapter on some devices.

I could zero out any values above say 500 TB since they're kinda ridiculous but I figured the raw driver value would be more useful?

**Comment by TETYYS** [comment]
I thought programs didn't always crash on uninitialized value reads, or microsoft did some protections?

**Comment by dmex** [comment]
I've changed the plugin to show N/A when the adapter is disconnected.
